{{- if .Values.ipam.enable -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: f5-ipam-controller
    release: {{ .Release.Name }}
  name: f5-ipam-controller
  namespace: {{ .Release.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f5-ipam-controller
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        app: f5-ipam-controller
    spec:
      containers:
      - args:
        - "--orchestration=kubernetes"
        - '--ip-range={{ .Values.ipam.ipRange | toJson }}'
        - "--log-level=DEBUG"
        command:
        - /app/bin/f5-ipam-controller
        image: {{ template "system_default_registry" . }}{{.Values.ipam.image.repository}}:{{.Values.ipam.image.tag}}
        imagePullPolicy: IfNotPresent
        terminationMessagePath: /dev/termination-log
        name: f5-ipam-controller
        volumeMounts:
        - mountPath: /app/ipamdb
          name: ipamvol
      serviceAccount: ipam-ctlr
      serviceAccountName: ipam-ctlr
      securityContext:
        fsGroup: 1200
        runAsGroup: 1200
        runAsUser: 1200
      volumes:
      - name: ipamvol
        persistentVolumeClaim:
          claimName: {{.Values.ipam.volume.pvc}}
{{- end -}}
